name: iyo_grocery_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.5.0
  flutter_gen: ^5.8.0
  flutter_svg: ^2.0.16
  form_builder_validators: ^11.0.0
  gap_here: ^1.0.0
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  vector_graphics: ^1.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  vector_graphics_compiler: ^1.1.16
  flutter_launcher_icons: ^0.14.1

flutter_gen:
  output: lib/core/ # Optional (default: lib/gen/)

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/items/
    - path: assets/svgs/
      transformers:
        - package: vector_graphics_compiler
